In [1]:
import numpy as np

In [2]:
#Create an array of 10 zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
#Create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
#Create an array of 10 fives
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [6]:
#Create an array of the integers from 10 to 50
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
#Create an array of all the even integers from 10 to 50
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [12]:
#Create a 3x3 matrix with values ranging from 0 to 8
arr=np.arange(9).reshape(3,3)


In [13]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
#Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
#Use NumPy to generate a random number between 0 and 1
np.random.rand(1)

array([0.47735138])

In [16]:
#Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution
np.random.randn(25)

array([-0.53187808,  1.529881  ,  0.09238623,  0.95392876, -0.64306436,
       -3.28347231,  1.06911585,  0.40493258, -0.24063794,  0.10721801,
       -1.6572862 ,  0.89671037,  0.01688462, -2.91000457, -1.37550623,
       -0.4125807 , -0.91793255, -1.75360735, -0.19890994, -0.26278851,
       -0.85925896,  0.89369536, -0.02895755,  0.75377409, -0.81427361])

In [21]:
#Create an array of 20 linearly spaced points between 0 and 1:
np.random.rand(20)

array([0.38987407, 0.76151463, 0.787224  , 0.42099742, 0.63232248,
       0.75366482, 0.88955358, 0.12379868, 0.76210424, 0.1739597 ,
       0.28052342, 0.30377621, 0.00850747, 0.15839298, 0.34408996,
       0.58219206, 0.30063741, 0.97324729, 0.40559604, 0.92754335])

In [1]:
import numpy as np

In [2]:
arr=np.arange(1,26).reshape(5,5)

In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY
matrix = np.array([[12, 13, 14, 15],
                   [17, 18, 19, 20],
                   [22, 23, 24, 25]])
print(matrix)

[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [8]:
matrix[1,3]

20

In [9]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [11]:
arr[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [12]:
arr[ 1:2]

array([[ 6,  7,  8,  9, 10]])

In [13]:
arr[0:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [14]:
np.arange(21,26)

array([21, 22, 23, 24, 25])

In [17]:
np.arange(16,26).reshape(2,5)

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [18]:
#get the sum of all the values in matrix
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
sum=arr.sum()
print(sum)

325


In [ ]:
7.2111025509279782????

In [20]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [21]:
arr[2,4]

15

In [24]:
np.arange(55,80,5)

array([55, 60, 65, 70, 75])